receivers:    
  jaeger:     
    protocols:
      thrift_compact:
exporters:
  otlp:
    endpoint: tempo:55680
    insecure: true
service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [otlp]