apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    name: grafana-datasources
  namespace: default
data:
  datasources.yaml: |-
    apiVersion: 1

    deleteDatasources:
      - name: Tempo
      - name: Loki

    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://tempo.default.svc.cluster.local:3100
        isDefault: true
        version: 1
        editable: true
        apiVersion: 1
        uid: tempo

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.default.svc.cluster.local:3100
