apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  labels:
    name: otel-config
  namespace: default
data:
  otel-collector.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp:
        endpoint: tempo:55680
        insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
